server:
  port: 80

logging:
  level:
    root: error
    org.jooq.tools.LoggerListener: info
    com.heony.coffee_order_collector: info
    org.springframework.web.client: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) [%thread] %cyan(%logger) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] [%thread] %logger - %msg%n"
  file:
    name: ./logs/logback.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/logback.%d{yyyy-MM-dd}.%i.log
      max-history: 30
      max-file-size: 20MB

spring:
  datasource:
    url: jdbc:sqlite:db/coffee.sqlite
    driver-class-name: org.sqlite.JDBC

  application:
    name: coffee-order-collector

  jooq:
    sql-dialect: sqlite

  threads:
    virtual:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

app:
  update-available:
    enabled: true
    timeout: 4
    timeunit: HOURS
#    timeunit : MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS

cafe:
  mammoth:
    domain: https://mmthcoffee.com
    path:
      menu-new: /sub/menu/new_list.php
      menu-express: /sub/menu/list.html
      menu-mammoth-coffee: /sub/menu/list_coffee.php

      details: /sub/menu/list_coffee_view.php?menuSeq=


springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: DESC
    operationsSorter: alpha
    persist-authorization: true
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

